{"name": "excel上传", "status": "broken", "statusDetails": {"message": "httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\ncheck_item: body.message\ncheck_value: 创建第1条标识: 88.408.13826286867/yes001失败,原因: 标识【88.408.13826286867/yes001】已存在;请修改后重新导入(str)\nassert_method: equal\nexpect_value: success(str)\nassert body.status equal 1(int)\t==> fail\ncheck_item: body.status\ncheck_value: -2(int)\nassert_method: equal\nexpect_value: 1(int)\nassert body.data equal True(bool)\t==> fail\ncheck_item: body.data\ncheck_value: False(bool)\nassert_method: equal\nexpect_value: True(bool)", "trace": "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:455: in test_start\n    return self.run_testcase(\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:357: in run_testcase\n    extract_mapping = self.__run_step(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:297: in __run_step\n    step_data = self.__run_step_testcase(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:251: in __run_step_testcase\n    .run()\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:384: in run\n    return self.run_testcase(testcase_obj)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:357: in run_testcase\n    extract_mapping = self.__run_step(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:295: in __run_step\n    step_data = self.__run_step_request(step)\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py:208: in __run_step_request\n    resp_obj.validate(\n/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/response.py:273: in validate\n    raise ValidationFailure(failures_string)\nE   httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\nE   check_item: body.message\nE   check_value: 创建第1条标识: 88.408.13826286867/yes001失败,原因: 标识【88.408.13826286867/yes001】已存在;请修改后重新导入(str)\nE   assert_method: equal\nE   expect_value: success(str)\nE   assert body.status equal 1(int)\t==> fail\nE   check_item: body.status\nE   check_value: -2(int)\nE   assert_method: equal\nE   expect_value: 1(int)\nE   assert body.data equal True(bool)\t==> fail\nE   check_item: body.data\nE   check_value: False(bool)\nE   assert_method: equal\nE   expect_value: True(bool)"}, "description": "TestCase ID: 848ab378-e6df-4f28-8b04-bef0ccffcf34", "steps": [{"name": "step: 登录-企业", "status": "passed", "steps": [{"name": "step: 登录-企业用户", "status": "passed", "start": 1687688160828, "stop": 1687688161122}], "start": 1687688160828, "stop": 1687688161123}, {"name": "step: 上传excel文件", "status": "broken", "statusDetails": {"message": "httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\ncheck_item: body.message\ncheck_value: 创建第1条标识: 88.408.13826286867/yes001失败,原因: 标识【88.408.13826286867/yes001】已存在;请修改后重新导入(str)\nassert_method: equal\nexpect_value: success(str)\nassert body.status equal 1(int)\t==> fail\ncheck_item: body.status\ncheck_value: -2(int)\nassert_method: equal\nexpect_value: 1(int)\nassert body.data equal True(bool)\t==> fail\ncheck_item: body.data\ncheck_value: False(bool)\nassert_method: equal\nexpect_value: True(bool)\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 357, in run_testcase\n    extract_mapping = self.__run_step(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 297, in __run_step\n    step_data = self.__run_step_testcase(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 251, in __run_step_testcase\n    .run()\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 384, in run\n    return self.run_testcase(testcase_obj)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 357, in run_testcase\n    extract_mapping = self.__run_step(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 295, in __run_step\n    step_data = self.__run_step_request(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 208, in __run_step_request\n    resp_obj.validate(\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/response.py\", line 273, in validate\n    raise ValidationFailure(failures_string)\n"}, "steps": [{"name": "step: 上传excel文件", "status": "broken", "statusDetails": {"message": "httprunner.exceptions.ValidationFailure: assert body.message equal success(str)\t==> fail\ncheck_item: body.message\ncheck_value: 创建第1条标识: 88.408.13826286867/yes001失败,原因: 标识【88.408.13826286867/yes001】已存在;请修改后重新导入(str)\nassert_method: equal\nexpect_value: success(str)\nassert body.status equal 1(int)\t==> fail\ncheck_item: body.status\ncheck_value: -2(int)\nassert_method: equal\nexpect_value: 1(int)\nassert body.data equal True(bool)\t==> fail\ncheck_item: body.data\ncheck_value: False(bool)\nassert_method: equal\nexpect_value: True(bool)\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 357, in run_testcase\n    extract_mapping = self.__run_step(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 295, in __run_step\n    step_data = self.__run_step_request(step)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/runner.py\", line 208, in __run_step_request\n    resp_obj.validate(\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/httprunner/response.py\", line 273, in validate\n    raise ValidationFailure(failures_string)\n"}, "start": 1687688161123, "stop": 1687688161392}], "start": 1687688161123, "stop": 1687688161394}], "attachments": [{"name": "stderr", "source": "3f63ad62-9cc2-498c-8512-026a96ae514b-attachment.txt", "type": "text/plain"}], "start": 1687688160825, "stop": 1687688161394, "uuid": "61c44324-13d2-4ed4-aeb3-a215aef7446b", "historyId": "defe879be1f5d991f7283f303185c53c", "testCaseId": "a1b3720e383dc8af54f061b97265ac8c", "fullName": "testsuites.uploadfile.test_upload_excel_test.TestCaseTestUploadExcel#test_start", "labels": [{"name": "parentSuite", "value": "testsuites.uploadfile"}, {"name": "suite", "value": "test_upload_excel_test"}, {"name": "subSuite", "value": "TestCaseTestUploadExcel"}, {"name": "host", "value": "shangjingjingdeMacBook-Pro.local"}, {"name": "thread", "value": "97352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testsuites.uploadfile.test_upload_excel_test"}]}